ymax=2


hist_info = {
	"met": {
		"xmin": 0,
		"xmax": 200,
		"binxmin": 0,
		"binxmax": 200,
		"ymin": 0,
		"ymax": ymax,
		"name": "met [GeV]",
		"bins": 10,
	},
	"ele1pt": {
		"xmin": 0,
		"xmax": 200,
		"binxmin": 0,
		"binxmax": 600,
		"ymin": 0,
		"ymax": ymax,
		"name": "Leading electron from Z  $P_{T}$ [GeV]",
		"bins": 30,
	},
	"ele2pt": {
		"xmin": 0,
		"xmax": 200,
		"binxmin": 0,
		"binxmax": 600,
		"ymin": 0,
		"ymax": ymax,
		"name": "Subleading electron from Z  $P_{T}$ [GeV]",
		"bins": 30,
	},
	"ele3pt": {
		"xmin": 0,
		"xmax": 200,
		"binxmin": 0,
		"binxmax": 600,
		"ymin": 0,
		"ymax": ymax,
		"name": "electron from W  $P_{T}$ [GeV]",
		"bins": 30,
	},
	"ele1eta": {
		"xmin": -3,
		"xmax": 3,
		"binxmin": -5,
		"binxmax": 5,
		"ymin": 0,
		"ymax": ymax,
		"name": "Leading Electron $\eta$",
		"bins": 20,
	},
	"ele2eta": {
		"xmin": -3,
		"xmax": 3,
		"binxmin": -5,
		"binxmax": 5,
		"ymin": 0,
		"ymax": ymax,
		"name": "SubLeading Electron $\eta$ ",
		"bins": 20,
	},
	"ele1phi": {
		"xmin": -3.15,
		"xmax": 3.15,
		"binxmin": -3.15,
		"binxmax": 3.15,
		"ymin": 0,
		"ymax": ymax,
		"name": "Leading Electron $\phi$",
		"bins": 10,
	},
	"ele2phi": {
		"xmin": -3.15,
		"xmax": 3.15,
		"binxmin": -3.15,
		"binxmax": 3.15,
		"ymin": 0,
		"ymax": ymax,
		"name": "SubLeading Electron $\phi$",
		"bins": 10,
	},
	"cutflow": {"xmin": 0, "xmax": 7, "ymin": 1, "ymax": 5e9},
	"mupt": {
		"xmin": 0,
		"xmax": 200,
		"binxmin": 0,
		"binxmax": 600,
		"ymin": 0,
		"ymax": ymax,
		"name": "electron from W  $P_{T}$ [GeV]",
		"bins": 30,
	},
	"mueta": {
		"xmin": -3,
		"xmax": 3,
		"binxmin": -5,
		"binxmax": 5,
		"ymin": 0,
		"ymax": ymax,
		"name": "Leading Muon $\eta$",
		"bins": 20,
	},
	"muphi": {
		"xmin": -3.15,
		"xmax": 3.15,
		"binxmin": -3.15,
		"binxmax": 3.15,
		"ymin": 0,
		"ymax": ymax,
		"name": "Leading Muon $\phi$ [GeV]",
		"bins": 10,
	},
	"pho_EB_pt": {
		"xmin": 0,
		"xmax": 200,
		"binxmin": 0,
		"binxmax": 600,
		"ymin": 0,
		"ymax": ymax,
		"name": "Photon EB $P_{T}$ [GeV]",
		"bins": 30,
	},
	"pho_EB_eta": {
		"xmin": -3,
		"xmax": 3,
		"binxmin": -5,
		"binxmax": 5,
		"ymin": 0,
		"ymax": ymax,
		"name": "Photon EB $\eta$ ",
		"bins": 25,
	},
	"pho_EB_phi": {
		"xmin": -3.15,
		"xmax": 3.15,
		"binxmin": -3.15,
		"binxmax": 3.15,
		"ymin": 0,
		"ymax": ymax,
		"name": "Photon EB $\phi$",
		"bins": 10,
	},
	"pho_EB_sieie": {
		"xmin": 0.006,
		"xmax": 0.012,
		"binxmin": 0,
		"binxmax": 0.012,
		"ymin": 0,
		"ymax": ymax,
		"name": "Photon EB sieie",
		"bins": 25,
	},
	"pho_EE_pt": {
		"xmin": 0,
		"xmax": 200,
		"binxmin": 0,
		"binxmax": 600,
		"ymin": 0,
		"ymax": ymax,
		"name": "Photon EE $P_{T}$ [GeV]",
		"bins": 30,
	},
	"pho_EE_eta": {
		"xmin": -3,
		"xmax": 3,
		"binxmin": -5,
		"binxmax": 5,
		"ymin": 0,
		"ymax": ymax,
		"name": "Photon EE $\eta$ ",
		"bins": 25,
	},
	"pho_EE_phi": {
		"xmin": -3.15,
		"xmax": 3.15,
		"binxmin": -3.15,
		"binxmax": 3.15,
		"ymin": 0,
		"ymax": ymax,
		"name": "Photon EE $\phi$",
		"bins": 10,
	},
	"pho_EE_sieie": {
		"xmin": 0.2,
		"xmax": 0.3,
		"binxmin": 0,
		"binxmax": 0.3,
		"ymin": 0,
		"ymax": ymax,
		"name": "Photon EE sieie",
		"bins": 50,
	},
	"mass": {
		"xmin": 0,
		"xmax": 200,
		"binxmin": 0,
		"binxmax": 200,
		"ymin": 0,
		"ymax": ymax,
		"name": "$M_{l1,l2}$ [GeV]",
		"bins": 10,
	},
	"MT": {
		"xmin": 0,
		"xmax": 200,
		"binxmin": 0,
		"binxmax": 200,
		"ymin": 0,
		"ymax": ymax,
		"name": "$MT_{met,l3}$ [GeV]",
		"bins": 10,
	},
}
